export const typedocOptions = {
	entryPoints: [
		"../lib/accessibility.ts",
		"../lib/generators.ts",
		"../lib/palettes.ts",
		"../lib/wrappers.ts",
		"../lib/utils.ts",
		"../lib/collection.ts",
		"../lib/types.d.ts",
	],
	excludeTags: ["@internal"],
	outputFileStrategy: "modules",
	fileExtension: ".mdx",
	expandObjects: true,
	tsconfig: "../tsconfig.json",
	excludeNotDocumented: true,
	excludeReferences: false,
	modulesFileName: undefined,
	entryModule: undefined,
	plugin: [
		"typedoc-plugin-markdown",
		"typedoc-plugin-frontmatter",
		"./plugin.mjs",
	],
	skipErrorChecking: true,
	frontmatterCommentTags: [
		"author",
		"description",
	],
	entryPointStrategy: "resolve",
	out: "docs/api",
	exclude: ["../lib/internal.ts"],
	groupOrder: [
		"Function",
		"Class",
		"Constructor",
		"Property",
		"Method",
		"TypeAlias",
	],
	hidePageTitle: true,
	hidePageHeader: true,
	hideGroupHeadings: false,
	cleanOutputDir: false,
	disableSources: false,

	readme: "none",
};
