name: Build Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

strategy:
  matrix: node-version:[12.x]

steps:
  - uses: actions/checkout@v2

  - name: Use NodeJS ${{matrix.node-version}}
    uses: actions/setup-node@v1
    with:
      node-version: ${{matrix.node-version}}

  - name: Install dependencies & build
    run: |
      npm ci
      npm run build

  - name: Deploy
    uses: peaceiris/actions/gh-pages@v3
    with:
      publish_dir: ./_site
      github_token: ${{secret.GITHUB_TOKEN}}
