import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { readdirSync } from 'node:fs';
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	guides: [{ type: 'autogenerated', dirName: 'guides' }],
	docs: [
		{
			type: 'category',
			label: 'Guides',
			link: {
				type: 'generated-index',
				title: 'Guides',
				description: 'Learn how to get started with color mnanipulation!',
				slug: '/guides',
				keywords: ['guides'],
				image: '/img/logo.png'
			},
			items: readdirSync('./docs/guides', 'utf-8').map(
				(post) => `guides/${post.split('.')[0]}`
			)
		}
	]

	// But you can create a sidebar manually

	// modules: [
	// 	{
	// 		type: 'category',
	// 		label: 'API',
	// 		items: [
	// 			{ type: 'doc', id: 'accessibility', label: 'Accessibility' },
	// 			{ type: 'doc', id: 'collection', label: 'Collection' },
	// 			{ type: 'doc', id: 'generators', label: 'Generators' },
	// 			{ type: 'doc', id: 'palettes', label: 'Palettes' },
	// 			{ type: 'doc', id: 'utils', label: 'Utils' },
	// 			{ type: 'doc', id: 'wrappers', label: 'Wrappers' }
	// 		]
	// 	}
	// ]
};

export default sidebars;
