import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import { readdirSync } from "node:fs";
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guides: [{ type: "autogenerated", dirName: "guides" }],
  docs: [
    {
      type: "category",
      label: "Guides",
      link: {
        type: "generated-index",
        title: "Guides",
        description: "Learn how to get started with color mnanipulation!",
        slug: "/guides",
        keywords: ["guides"],
        image: "/img/logo.png",
      },
      items: readdirSync("./docs/guides", "utf-8").map(
        (post) => `guides/${post.split(".")[0]}`
      ),
    },

    {
      type: "category",
      label: "Guides",
      link: {
        type: "generated-index",
        title: "API",
        description:
          "Learn how to use the exported symbols (like functions or classes) in your code.",
        slug: "/api",
        keywords: [
          "api",
          "docs",
          "functions",
          "palettes",
          "generators",
          "accessibility",
          "collection",
          "wrappers",
        ],
        image: "/img/logo.png",
      },
      items: readdirSync("./docs/api", "utf-8")
        .filter(
          (file) =>
            !["typedoc-sidebar.cjs", "module_index.mdx", "index.mdx"].some(
              (f) => f === file
            )
        )
        .map((post) => `api/${post.split(".")[0]}`),
    },
  ],
};

export default sidebars;
